# -*- coding: utf-8 -*-
"""Eliezer_MolinaMello_Assignment_4_Python_Code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q3FVv4ntVLom_lc7EFxZnNOKeuxKVQ52

## Python Code for Visualization 1 - Daily Shelter & Overnight Service Occupancy

### Getting Data

I've chosen the Daily Shelter Overnight Service Occupancy and Capacity data. Retrieved from https://open.toronto.ca/dataset/daily-shelter-overnight-service-occupancy-capacity/

### Getting Started

#### 0. Loading Python packages
"""

# Import packages
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

# Display all columns
pd.set_option("display.max_columns", None)

# Connecting to my personal Google Drive
from google.colab import drive
drive.mount('/content/drive')

"""#### 1. Load Data as DataFrame"""

shelter_capacity = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data_viz/daily_shelter_occupancy_2023.csv')

"""#### 2. Profile the DataFrame"""

# Dataset columns
shelter_capacity.columns

# Dtypes for extra info
shelter_capacity.info()

# Converting occupancy_date to date type in case we use it in our visualization
shelter_capacity['OCCUPANCY_DATE'] = pd.to_datetime(shelter_capacity['OCCUPANCY_DATE'])
shelter_capacity['OCCUPANCY_DATE'].info()

"""### Plotting the data"""

# Using head() to remember our data
shelter_capacity.head(2)

# First try at plotting our data

# Using the darkgrid style
sns.set_style('darkgrid')

# Plotting occupancy date and rate
sns.lineplot(data=shelter_capacity,
             x='OCCUPANCY_DATE',
             y='OCCUPANCY_RATE_BEDS')

# Second try at plotting the shelter data

# Making the figure longer to better display the dates
fig = plt.subplots(figsize=(12,3))

# Specifying the axes and line styles
sheltergraph = sns.lineplot(data=shelter_capacity,
                        x='OCCUPANCY_DATE',
                        y='OCCUPANCY_RATE_BEDS',
                        color = 'black',
                        linestyle = '-',
                        linewidth = 1)

# Specifying title and data labels
sheltergraph.set(title = '2023 Shelter Occupancy Rates',
             xlabel = 'Occupancy Date',
             ylabel = 'Occupancy Rate (%)')

# Show visualization without text
plt.show()